github.com:
    users:
        park102:
            oauth_token: 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
    git_protocol: https
    user: park102
    oauth_token: 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
