[window]
opacity = 0.7

[env]
TERM = "xterm-256color"

[font.bold]
family = "DejaVuSansM Nerd Font Mono"
style = "Bold"

[font.italic]
family = "DejaVuSansM Nerd Font Mono"

[font.normal]
family = "DejaVuSansM Nerd Font Mono"
style = "Regular"

[font]
size = 12

